### PR TITLE
Update appsettings.json

### PR DESCRIPTION
**Pull request by GeoGerrit**
Set Planner to "Stepwise"

### Contribution Checklist

- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [Contribution Guidelines](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] All unit tests pass, and I have added new tests where possible
- [ ] I didn't break anyone :smile:

### CODE REVIEW

**Comment by GeoGerrit** [comment]
@gormaar  I only made one change -- curious to hear if this is the right way and how we can re-deploy the app.

**Comment by gormaar** [comment]
@GeoGerrit we need to update the repository secrets to target our app, and make federated credentials for it to continuously deploy. I can add this as backlog items

**Comment by GeoGerrit** [comment]
@gormaar Can you deploy this one manually?

**Comment by gormaar** [comment]
Yes, will do!

**Pull request merged**
